### ISSUE TITLE
Update package name to instrumental_agent

### ISSUE THREAD

**Issue by jason-o-matic** [Instrumental/instrumental_agent-node#11]
We released this before we discussed how we wanted to name our packages. We should update the package unless there's a good reason not to.

Here's the current: https://www.npmjs.com/package/instrumental-node

Some helpful info on package renaming:
http://stackoverflow.com/questions/28371669/renaming-a-published-npm-module
https://docs.npmjs.com/cli/deprecate
https://www.gregjs.com/javascript/2016/how-to-rename-a-published-npm-module/

**Comment by janxious** [comment]
Is this done, or are you planning to do it?

**Comment by jason-o-matic** [comment]
I haven't done it yet because I don't want the current users to have a bad experience. I suspect if we just rename the package and nothing else that customer deploys will fail. We should verify that. If so perhaps there is a way to deprecate the old package.

**Comment by janxious** [comment]
It is done!
