### ISSUE TITLE
module version mismatch

### ISSUE THREAD

**Issue by spacetc62** [Instrumental/instrumental_agent-node#12]
https://www.npmjs.com/package/instrumental-node says the module is at version 1.0.0, but the code in this repo is only at version 0.2.0 (https://github.com/Instrumental/instrumental_agent-node/blob/master/package.json#L3).  What is correct?  Doesn't look like the package is at v1.0.0 in any tags or branches either.

**Comment by janxious** [comment]
Looks like the CHANGELOG was not updated and the release instructions were not followed with regards to tagging. 🙄

I'll get a version with those things out.

**Comment by jason-o-matic** [comment]
My bad, I hadn't pushed the version bump commit. It's up now.
