### ISSUE TITLE
node.js 10.x support?

### ISSUE THREAD

**Issue by alecgorge** [Instrumental/instrumental_agent-node#22]
In `package.json` it seems that node.js 10.x support is explicitly removed: `"node": ">=5.1 <10"`.

Is there a reason for this? The 10.x branch is a LTS branch and will be supported until 2021.

**Comment by janxious** [comment]
Something changed between 9 and 10 in a stdlib or other call we are using and we haven't had time to investigate the failure yet. It shows up in the tests if run under node 10. We are open to PRs to fix it. 👍
